### ISSUE TITLE
How to compile on Windows?

### ISSUE THREAD

**Issue by Monkeybin11** [6Morpheus6/deepspeed-windows-wheels#1]
Could you tell me how you managed to compile it successfully on Windows? I’m currently trying to build PyTorch 2.7.1 with CUDA 12.8 and keep running into errors.

[2025-08-05 00:29:29] C:\ProgramData\miniconda3\envs\agpt_env\Lib\site-packages\torch\include\torch/csrc/distributed/c10d/NCCLUtils.hpp(5): fatal error C1083: 无法打开包括文件: “sched.h”: No such file or directory
[2025-08-05 00:29:29] error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.44.35207\\bin\\HostX64\\x64\\cl.exe' failed with exit code 2
[2025-08-05 00:29:30] [0m
[2025-08-05 00:29:30] Build process error: Build failed
[2025-08-05 00:29:30] Error during build: Build failed

**Comment by 6Morpheus6** [comment]
Hi @Monkeybin11 
Sorry for that late reply. I just saw it today.

Add these 2 environment variables and your build should run through.
`set DS_BUILD_SPARSE_ATTN=0`
`set DS_BUILD_DEEP_COMPILE=0`

But the DeepSpeed version I released is compatible with pytorch 2.7.x It will also work on pytorch 2.7.1
I tried to improve the readme. I wasn't clear on this point.
Additionally I released wheels for pytorch 2.8.0 today.

**Comment by Thireus** [comment]
Here's what worked for me:

```
# Install Cuda12.8 - https://developer.nvidia.com/cuda-12-8-0-download-archive?target_os=Windows&target_arch=x86_64&target_version=11&target_type=exe_network
# Install Visual Studio Community 2022 - https://visualstudio.microsoft.com/vs/community/
# You should download the VS exe anyway and execute it to see if there are updates of your toolkit!

# Open Powershell
mkdir C:\MyProject
cd C:\MyProject
python -m venv env
env\Scripts\activate
#pip install torch==2.7.0 torchvision==0.22.0 torchaudio==2.7.0 --index-url https://download.pytorch.org/whl/cu128
pip install torch torchvision torchaudio --force-reinstall --index-url https://download.pytorch.org/whl/cu128
pip install setuptools wheel ninja packaging py-cpuinfo psutil
pip install tqdm pydantic msgpack hjson einops
git clone https://github.com/deepspeedai/DeepSpeed

# Open x64 Native Tools Command Prompt for VS 2022
cd C:\Myproject
call env\Scripts\activate
set DISTUTILS_USE_SDK=1
set CUDA_HOME=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.8
set TORCH_CUDA_ARCH_LIST=8.6;12.0
set DS_BUILD_OPS=1
set DS_BUILD_GDS=0
set DS_BUILD_AIO=0
set DS_BUILD_CUTLASS_OPS=0
set DS_BUILD_SPARSE_ATTN=0
set DS_BUILD_SPARSE_UTILS=0
set DS_BUILD_FP_QUANTIZER=0
set DS_BUILD_DEEP_COMPILE=0
set DS_BUILD_EVOFORMER_ATTN=0
set DS_BUILD_RAGGED_DEVICE_OPS=0
cd DeepSpeed
python setup.py bdist_wheel
```
